'use strict';
const $=id=>document.getElementById(id);
const message=text=>{$('message').textContent=text;};
async function request(body){const r=await fetch('/api/boutique',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});let data;try{data=await r.json();}catch{throw Error('The server did not return a studio response. Please check the deployment.');}if(!r.ok)throw Error(data.error||'Something went wrong.');return data;}
if($('login')){$('login').addEventListener('submit',async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;message('Opening the studio…');try{await request({action:'login',password:$('password').value});location.reload();}catch(err){message(err.message);}finally{b.disabled=false;}});}
if($('brief')){
  const ids=['film','style','scene','dialogue','references','continuity','duration','aspect','surface','coverage','revision'];
  let questions=[],history=[],result=null,busy=false;
  function save(){try{sessionStorage.setItem('lbp-draft',JSON.stringify({fields:Object.fromEntries(ids.map(id=>[id,$(id).value])),history}));}catch{}}
  try{const saved=JSON.parse(sessionStorage.getItem('lbp-draft')||'null');if(saved){for(const id of ids)if(typeof saved.fields?.[id]==='string')$(id).value=saved.fields[id];if(Array.isArray(saved.history))history=saved.history;}}catch{}
  function invalidate(){result=null;$('result').hidden=true;}
  function collect(){return questions.map((q,i)=>({question:q.title,answer:document.querySelector('input[name="q'+i+'"]:checked')?.value||''}));}
  function payload(action){const answers=collect();if(answers.some(a=>!a.answer.trim()))throw Error('Please answer each question, or choose its recommendation.');const combined=[...history,...answers].slice(-30);return {...Object.fromEntries(ids.map(id=>[id,$(id).value])),action,answers:combined};}
  function element(tag,text,cls){const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(cls)el.className=cls;return el;}
  function showQuestions(items){questions=items;$('questions').replaceChildren();items.forEach((q,i)=>{const fs=element('fieldset',undefined,'question');fs.append(element('legend',(i+1)+'. '+q.title),element('p',q.why,'hint'));const choices=element('div',undefined,'choices');q.options.forEach((option,j)=>{const label=element('label',undefined,'choice');const radio=document.createElement('input');radio.type='radio';radio.name='q'+i;radio.value=option;const text=element('span',option);if(j===q.recommendedIndex)text.append(element('em','DIRECTOR’S RECOMMENDATION'));label.append(radio,text);radio.addEventListener('change',invalidate);choices.append(label);});const custom=document.createElement('input');custom.placeholder='Or write your own direction…';custom.maxLength=2000;custom.setAttribute('aria-label','Custom answer to '+q.title);const label=element('label',undefined,'choice');const radio=document.createElement('input');radio.type='radio';radio.name='q'+i;radio.setAttribute('aria-label','Use custom answer');custom.addEventListener('input',()=>{radio.value=custom.value;radio.checked=true;invalidate();});label.append(radio,custom);choices.append(label);fs.append(choices);$('questions').append(fs);});}
  function pack(){return ['LITTLE BOUTIQUE PRODUCTIONS',...['settings','referenceMap'].map(k=>k.toUpperCase()+'\n'+result[k]),...result.clips.map(c=>c.title+'\n'+c.prompt),'RISK NOTES\n'+result.risks.join('\n')].join('\n\n');}
  async function copy(text,button){try{await navigator.clipboard.writeText(text);const old=button.textContent;button.textContent='Copied ✓';setTimeout(()=>button.textContent=old,1800);}catch{message('Clipboard access was unavailable. Select the prompt text or download the pack.');}}
  function showResult(data){result=data;$('output').replaceChildren();$('validation').replaceChildren();const sections=[['Generation settings',data.settings],['Reference map',data.referenceMap],...data.clips.map(c=>[c.title,c.prompt]),['Risk notes',data.risks.join('\n')]];sections.forEach(([title,text])=>{if(!text)return;const heading=element('div',undefined,'output-label');heading.append(element('h3',title));const button=element('button','Copy','secondary');button.onclick=()=>copy(text,button);heading.append(button);$('output').append(heading,element('pre',text));});$('validation').append(element('div','Review the prompt and bind every reference in Higgsfield before generating. These are directing instructions, not a tested render.','validation-note'));$('result').hidden=false;$('step3').classList.add('active');$('result').scrollIntoView({behavior:'smooth',block:'start'});}
  async function run(action){if(busy)return;let body;try{body=payload(action);}catch(e){message(e.message);return;}if(!$('scene').value.trim()){message('Describe your scene first.');$('scene').focus();return;}busy=true;document.querySelectorAll('button,input,textarea,select').forEach(x=>x.disabled=true);message(action==='review'?'Your director is reading the scene and finding the decisions that matter…':'Building your prompt: checking emotion, physical action, and continuity…');save();try{const data=await request(body);history=body.answers;showQuestions(data.questions);$('feedback').textContent=data.feedback;$('direction').hidden=false;$('step2').classList.add('active');if(data.clips.length)showResult(data);else{invalidate();$('direction').scrollIntoView({behavior:'smooth',block:'start'});}save();message(data.questions.length?'Choose the direction that feels right. Recommendations are optional.':'Direction updated. '+(data.clips.length?'Your prompt pack is ready to review.':'Build your prompt when ready.'));}catch(e){message(e.message);}finally{busy=false;document.querySelectorAll('button,input,textarea,select').forEach(x=>x.disabled=false);}}
  $('brief').onsubmit=e=>{e.preventDefault();run('review');};$('refine').onclick=()=>run('review');$('generate').onclick=()=>run('generate');
  ids.forEach(id=>$(id).addEventListener('input',()=>{invalidate();if(id!=='revision'){history=[];showQuestions([]);$('direction').hidden=true;$('step2').classList.remove('active');$('step3').classList.remove('active');}save();}));
  $('copy-all').onclick=e=>{if(result)copy(pack(),e.target);};$('download').onclick=()=>{if(!result)return;const url=URL.createObjectURL(new Blob([pack()],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download='little-boutique-prompt.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  $('new-scene').onclick=()=>{if($('scene').value&&!confirm('Start a new scene? Download any prompt you want to keep first.'))return;for(const id of ['scene','dialogue','references','continuity','revision'])$(id).value='';history=[];showQuestions([]);invalidate();$('direction').hidden=true;$('step2').classList.remove('active');$('step3').classList.remove('active');save();message('A fresh page. What happens next?');$('scene').focus();};
  $('logout').onclick=async()=>{try{save();await request({action:'logout'});location.reload();}catch(e){message(e.message);}};
}
